I386_COMMON_C_SRCS = \
	hal/early.c \
	kernel/core/early_console.c \
	kernel/core/early_kprint.c \
	kernel/core/kprint.c \
	kernel/core/boot_log.c \
	kernel/core/boot_state.c \
	kernel/core/kernel_root.c \
	kernel/core/kernel_config.c \
	kernel/core/early_boot.c \
	kernel/core/early_runtime_hooks.c \
	kernel/core/kernel_init_flow.c \
	kernel/core/clipboard.c \
	kernel/core/console.c \
	kernel/core/tty.c \
	kernel/core/tty_ansi.c \
	kernel/core/tty_hangul.c \
	kernel/core/tty_input.c \
	kernel/core/tty_line_edit.c \
	kernel/core/tty_queue.c \
	kernel/core/tty_utf8.c \
	kernel/core/tty_virtual.c \
	kernel/core/graphics_service.c \
	kernel/core/profile.c \
	kernel/core/system_query.c \
	kernel/core/system_power.c \
	arch/x86/i386/services/boot_flags.c \
	arch/x86/i386/services/boot_user.c \
	arch/x86/i386/services/shared.c \
	arch/x86/i386/services/command.c \
	arch/x86/i386/services/driver.c \
	arch/x86/i386/services/input.c \
	arch/x86/i386/services/console_loop.c \
	arch/x86/i386/services/smoke.c \
	arch/x86/i386/services/tty_selftest.c \
	arch/x86/i386/syscall/compat32.c \
	arch/x86/i386/syscall/compat32_copy_ops.c \
	kernel/sys/syscall_common_request_core.c \
	arch/x86/i386/syscall/compat32_request_adapter.c \
	arch/x86/i386/syscall/compat32_file_ops.c \
	arch/x86/i386/syscall/compat32_io_adapter.c \
	arch/x86/i386/syscall/compat32_fs_adapter.c \
	arch/x86/i386/syscall/compat32_mount_adapter.c \
	arch/x86/i386/syscall/compat32_proc_adapter.c \
	arch/x86/i386/syscall/compat32_vm_adapter.c \
	arch/x86/i386/syscall/compat32_vm_page_ops.c \
	arch/x86/i386/syscall/compat32_job_adapter.c \
	arch/x86/i386/syscall/compat32_mem_adapter.c \
	arch/x86/i386/syscall/compat32_ipc_adapter.c \
	arch/x86/i386/syscall/compat32_query_adapter.c \
	arch/x86/i386/syscall/compat32_gfx_adapter.c \
	arch/x86/i386/syscall/compat32_audio_adapter.c \
	arch/x86/i386/syscall/compat32_audio_fd_adapter.c \
	arch/x86/i386/syscall/compat32_block_adapter.c \
	arch/x86/i386/syscall/compat32_net_adapter.c \
	arch/x86/i386/syscall/compat32_ui_adapter.c \
	arch/x86/i386/syscall/compat32_misc_adapter.c \
	arch/x86/i386/syscall/compat32_proc.c \
	kernel/proc/boot_user_init.c \
	kernel/proc/process_context.c \
	kernel/proc/process_command.c \
	kernel/proc/process_model.c \
	kernel/proc/process_mm_query.c \
	kernel/proc/process_program_registry.c \
	kernel/proc/process_user_backend.c \
	kernel/proc/process_mm_ops.c \
	kernel/mem/address_space_core.c \
	kernel/sched/process_scheduler_ops.c \
	arch/x86/i386/scheduler/policy.c \
	kernel/sched/runqueue.c \
	kernel/driver/driver.c \
	arch/x86/i386/driver/services.c \
	arch/x86/i386/driver/elf_loader.c \
	kernel/fs/fs_service_root_query.c \
	kernel/fs/fs_service_path.c \
	kernel/fs/fs_service_fd.c \
	kernel/fs/path_resolve.c \
	kernel/fs/file.c \
	kernel/fs/file_backend.c \
	kernel/fs/file_device_backend.c \
	kernel/fs/file_pipe_backend.c \
	$(I386_DRIVER_C_SRCS) \
	$(I386_FS_C_SRCS) \
	lib/parse.c \
	lib/string.c \
	user/libc32/std/div64.c
I386_ARCH_C_SRCS := \
	arch/x86/i386/gdt.c \
	arch/x86/i386/idt.c \
	arch/x86/i386/keyboard.c \
	arch/x86/common/pic.c \
	arch/x86/common/arch_ops.c \
	arch/x86/i386/mm/paging.c \
	arch/x86/i386/mm/pmm.c \
	arch/x86/i386/mm/vmm.c \
	arch/x86/i386/context.c \
	arch/x86/i386/scheduler/scheduler.c \
	arch/x86/i386/process/process.c \
	arch/x86/i386/process/address_space.c \
	arch/x86/i386/user.c \
	arch/x86/i386/ops.c \
	hal/i386/platform.c \
	arch/x86/i386/platform_boot.c
I386_ARCH_ASM_SRCS := \
	arch/x86/i386/entry.asm \
	arch/x86/i386/gdt_flush.asm \
	arch/x86/i386/isr.asm
