I386_COMMON_C_SRCS = \
	hal/early.c \
	kernel/core/early_console.c \
	kernel/core/early_kprint.c \
	kernel/core/kprint.c \
	kernel/core/boot_log.c \
	kernel/core/boot_state.c \
	kernel/core/early_boot.c \
	kernel/core/early_runtime_hooks.c \
	kernel/core/kernel_init_flow.c \
	kernel/core/clipboard.c \
	kernel/core/console.c \
	kernel/core/tty.c \
	kernel/core/tty_ansi.c \
	kernel/core/tty_hangul.c \
	kernel/core/tty_input.c \
	kernel/core/tty_line_edit.c \
	kernel/core/tty_queue.c \
	kernel/core/tty_utf8.c \
	kernel/core/tty_virtual.c \
	kernel/core/graphics_service.c \
	kernel/core/profile.c \
	kernel/core/system_query.c \
	kernel/core/i386_shared_services.c \
	kernel/core/i386_smoke_services.c \
	kernel/core/i386_tty_selftest.c \
	kernel/sys/syscall_compat32.c \
	kernel/sys/syscall_common_request_core.c \
	kernel/sys/syscall_i386_request_adapter.c \
	kernel/sys/syscall_i386_vm_adapter.c \
	kernel/sys/syscall_i386_job_adapter.c \
	kernel/sys/syscall_i386_mem_ipc_adapter.c \
	kernel/sys/syscall_i386_device_ui_adapter.c \
	kernel/sys/syscall_compat32_query.c \
	kernel/sys/syscall_compat32_fs.c \
	kernel/sys/syscall_compat32_proc.c \
	kernel/proc/boot_user_init.c \
	kernel/proc/process_context.c \
	kernel/proc/process_command.c \
	kernel/proc/process_model.c \
	kernel/proc/process_program_registry.c \
	kernel/proc/process_user_backend.c \
	kernel/proc/process_mm_ops.c \
	kernel/proc/process_file_ops.c \
	kernel/mem/address_space_core.c \
	kernel/sched/process_scheduler_ops.c \
	kernel/sched/sched_policy.c \
	kernel/sched/runqueue.c \
	kernel/driver/driver.c \
	kernel/driver/driver_i386_services.c \
	kernel/driver/driver_i386_legacy.c \
	kernel/fs/path_resolve.c \
	kernel/fs/file.c \
	kernel/fs/file_backend.c \
	kernel/fs/file_device_backend.c \
	kernel/fs/file_pipe_backend.c \
	$(I386_DRIVER_C_SRCS) \
	$(I386_FS_C_SRCS) \
	lib/string.c \
	user/libc32/std/div64.c
I386_ARCH_C_SRCS := \
	arch/x86/i386/gdt.c \
	arch/x86/i386/idt.c \
	arch/x86/i386/keyboard.c \
	arch/x86/common/pic.c \
	arch/x86/common/arch_ops.c \
	arch/x86/i386/paging.c \
	arch/x86/i386/pmm.c \
	arch/x86/i386/vmm.c \
	arch/x86/i386/context.c \
	arch/x86/i386/scheduler.c \
	arch/x86/i386/process32.c \
	arch/x86/i386/process32_address_space.c \
	arch/x86/i386/user.c \
	arch/x86/i386/ops.c \
	hal/i386/platform.c \
	arch/x86/i386/platform_boot.c
I386_ARCH_ASM_SRCS := \
	arch/x86/i386/entry.asm \
	arch/x86/i386/gdt_flush.asm \
	arch/x86/i386/isr.asm
