#pragma once

#include "abi/syscall_abi.h"

extern int errno;

#define EPERM NEX_ERR_PERM
#define ENOENT NEX_ERR_NOENT
#define ESRCH NEX_ERR_SRCH
#define EIO NEX_ERR_IO
#define ENOEXEC NEX_ERR_NOEXEC
#define ECHILD NEX_ERR_CHILD
#define EAGAIN NEX_ERR_AGAIN
#define ENOMEM NEX_ERR_NOMEM
#define EACCES NEX_ERR_ACCES
#define EEXIST NEX_ERR_EXIST
#define ENOTDIR NEX_ERR_NOTDIR
#define EISDIR NEX_ERR_ISDIR
#define EINVAL NEX_ERR_INVAL
#define EFBIG NEX_ERR_FBIG
#define ENOSPC NEX_ERR_NOSPC
#define EPIPE NEX_ERR_PIPE
#define ENOSYS NEX_ERR_NOSYS

#define ENEXEXEC NEX_ERR_EXEC
#define ENEXBADELF NEX_ERR_BAD_ELF
