#pragma once

#include <stdint.h>

enum keyboard_keycode {
    KEYBOARD_KEY_NONE = 0,
    KEYBOARD_KEY_ESC,
    KEYBOARD_KEY_TAB,
    KEYBOARD_KEY_ENTER,
    KEYBOARD_KEY_BACKSPACE,
    KEYBOARD_KEY_SPACE,
    KEYBOARD_KEY_HOME,
    KEYBOARD_KEY_END,
    KEYBOARD_KEY_DELETE,
    KEYBOARD_KEY_PAGE_UP,
    KEYBOARD_KEY_PAGE_DOWN,
    KEYBOARD_KEY_UP,
    KEYBOARD_KEY_DOWN,
    KEYBOARD_KEY_LEFT,
    KEYBOARD_KEY_RIGHT,
    KEYBOARD_KEY_LEFT_SHIFT,
    KEYBOARD_KEY_RIGHT_SHIFT,
    KEYBOARD_KEY_LEFT_CTRL,
    KEYBOARD_KEY_RIGHT_CTRL,
    KEYBOARD_KEY_CAPS_LOCK,
    KEYBOARD_KEY_A,
    KEYBOARD_KEY_B,
    KEYBOARD_KEY_C,
    KEYBOARD_KEY_D,
    KEYBOARD_KEY_E,
    KEYBOARD_KEY_F,
    KEYBOARD_KEY_G,
    KEYBOARD_KEY_H,
    KEYBOARD_KEY_I,
    KEYBOARD_KEY_J,
    KEYBOARD_KEY_K,
    KEYBOARD_KEY_L,
    KEYBOARD_KEY_M,
    KEYBOARD_KEY_N,
    KEYBOARD_KEY_O,
    KEYBOARD_KEY_P,
    KEYBOARD_KEY_Q,
    KEYBOARD_KEY_R,
    KEYBOARD_KEY_S,
    KEYBOARD_KEY_T,
    KEYBOARD_KEY_U,
    KEYBOARD_KEY_V,
    KEYBOARD_KEY_W,
    KEYBOARD_KEY_X,
    KEYBOARD_KEY_Y,
    KEYBOARD_KEY_Z,
    KEYBOARD_KEY_0,
    KEYBOARD_KEY_1,
    KEYBOARD_KEY_2,
    KEYBOARD_KEY_3,
    KEYBOARD_KEY_4,
    KEYBOARD_KEY_5,
    KEYBOARD_KEY_6,
    KEYBOARD_KEY_7,
    KEYBOARD_KEY_8,
    KEYBOARD_KEY_9,
    KEYBOARD_KEY_MINUS,
    KEYBOARD_KEY_EQUAL,
    KEYBOARD_KEY_LEFT_BRACKET,
    KEYBOARD_KEY_RIGHT_BRACKET,
    KEYBOARD_KEY_BACKSLASH,
    KEYBOARD_KEY_SEMICOLON,
    KEYBOARD_KEY_APOSTROPHE,
    KEYBOARD_KEY_GRAVE,
    KEYBOARD_KEY_COMMA,
    KEYBOARD_KEY_PERIOD,
    KEYBOARD_KEY_SLASH
};

struct keyboard_event {
    enum keyboard_keycode keycode;
    char ascii;
    uint8_t pressed;
    uint8_t released;
    uint8_t extended;
    uint8_t shift;
    uint8_t ctrl;
    uint8_t caps_lock;
};
