#pragma once

enum {
    NOS_PAGE_SIZE = 4096u,
    NOS_KERNEL_STACK_SIZE = 16384u,
    NOS_TTY_LINE_MAX = 255u,
    NOS_TTY_LINE_BUFFER_SIZE = NOS_TTY_LINE_MAX + 1u,
    NOS_PATH_MAX = 255u,
    NOS_PATH_BUFFER_SIZE = NOS_PATH_MAX + 1u,
    NOS_NAME_MAX = 255u,
    NOS_NAME_BUFFER_SIZE = NOS_NAME_MAX + 1u,
    NOS_MOUNT_SLOT_MAX = 4u,
    NOS_PROCESS_SLOT_MAX = 4u,
    NOS_PROCESS_FILE_MAX = 16u,
    NOS_ELF_FILE_BUFFER_SIZE = 262144u,
    NOS_USER_STACK_SIZE = NOS_PAGE_SIZE
};
